-- Pre-release initial schema. Edit in place until Phase 1 is deployed.
CREATE TABLE sessions (session_id TEXT PRIMARY KEY, last_seq INTEGER NOT NULL DEFAULT 0, committed INTEGER NOT NULL DEFAULT 0);
CREATE TABLE rec_item (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_event_id TEXT,
  f_directive_id TEXT,
  f_section TEXT,
  f_seq INTEGER,
  f_workflow_id TEXT,
  f_task_id TEXT,
  f_agent_id TEXT,
  f_turn_id TEXT,
  f_kind TEXT,
  f_generation TEXT,
  f_authority TEXT,
  f_scope TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  f_residency TEXT,
  f_goal_status_present INTEGER NOT NULL DEFAULT 0,
  f_goal_status TEXT,
  f_retention TEXT,
  f_parts TEXT,
  f_content_hash TEXT,
  f_semantic_bytes INTEGER,
  f_importance INTEGER,
  f_created_at TEXT,
  f_last_used_call INTEGER,
  f_access_count INTEGER,
  f_ttl_turns_present INTEGER NOT NULL DEFAULT 0,
  f_ttl_turns INTEGER,
  f_tags TEXT,
  f_source_present INTEGER NOT NULL DEFAULT 0,
  f_source_kind TEXT,
  f_source_locator TEXT,
  f_source_content_hash TEXT,
  f_source_tool_call_id TEXT,
  f_version INTEGER,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_relationship (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_type TEXT,
  f_from_id TEXT,
  f_to_id TEXT,
  f_seq INTEGER,
  f_authority TEXT,
  f_event_id TEXT,
  f_rule_version TEXT,
  f_coverage_present INTEGER NOT NULL DEFAULT 0,
  f_coverage_conversation_id TEXT,
  f_coverage_from_seq INTEGER,
  f_coverage_to_seq INTEGER,
  f_coverage_item_ids TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_event (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_principal_session_id TEXT,
  f_principal_workflow_id TEXT,
  f_principal_task_id TEXT,
  f_principal_agent_id TEXT,
  f_principal_authority TEXT,
  f_payload_hash TEXT,
  f_source_hash TEXT,
  f_seq INTEGER,
  f_item_ids TEXT,
  f_committed_at TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_obligation (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_task_id TEXT,
  f_source_item_id TEXT,
  f_source_authority TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  f_description TEXT,
  f_matcher_present INTEGER NOT NULL DEFAULT 0,
  f_matcher_name TEXT,
  f_matcher_version TEXT,
  f_status TEXT,
  f_current INTEGER,
  f_evidence_ids TEXT,
  f_created_seq INTEGER,
  f_retired_seq INTEGER,
  f_materialization_disabled INTEGER,
  f_revision INTEGER,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_obligation_transition (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_obligation_id TEXT,
  f_version INTEGER,
  f_seq INTEGER,
  f_from TEXT,
  f_to TEXT,
  f_action TEXT,
  f_actor_session_id TEXT,
  f_actor_workflow_id TEXT,
  f_actor_task_id TEXT,
  f_actor_agent_id TEXT,
  f_actor_authority TEXT,
  f_grant_id TEXT,
  f_matcher_present INTEGER NOT NULL DEFAULT 0,
  f_matcher_name TEXT,
  f_matcher_version TEXT,
  f_evidence_ids TEXT,
  f_fingerprints TEXT,
  f_reason TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_grant (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_action TEXT,
  f_target_ids TEXT,
  f_issuer_session_id TEXT,
  f_issuer_workflow_id TEXT,
  f_issuer_task_id TEXT,
  f_issuer_agent_id TEXT,
  f_issuer_authority TEXT,
  f_grantee_present INTEGER NOT NULL DEFAULT 0,
  f_grantee_session_id TEXT,
  f_grantee_workflow_id TEXT,
  f_grantee_task_id TEXT,
  f_grantee_agent_id TEXT,
  f_grantee_authority TEXT,
  f_matcher_present INTEGER NOT NULL DEFAULT 0,
  f_matcher_name TEXT,
  f_matcher_version TEXT,
  f_issued_seq INTEGER,
  f_expires_at_seq INTEGER,
  f_revoked_seq INTEGER,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_task (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_workflow_id TEXT,
  f_status TEXT,
  f_turn INTEGER,
  f_turn_id TEXT,
  f_completed_seq INTEGER,
  f_version INTEGER,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_lifecycle (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_seq INTEGER,
  f_target_kind TEXT,
  f_target_id TEXT,
  f_action TEXT,
  f_from TEXT,
  f_to TEXT,
  f_actor_session_id TEXT,
  f_actor_workflow_id TEXT,
  f_actor_task_id TEXT,
  f_actor_agent_id TEXT,
  f_actor_authority TEXT,
  f_grant_id TEXT,
  f_event_id TEXT,
  f_reason TEXT,
  f_payload_hash TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_conversation (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_task_id TEXT,
  f_agent_id TEXT,
  f_version INTEGER,
  f_epoch INTEGER,
  f_logical_calls INTEGER,
  f_in_flight_call_id TEXT,
  f_require_new_epoch INTEGER,
  f_revision INTEGER,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_call (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_conversation_id TEXT,
  f_operation TEXT,
  f_state TEXT,
  f_principal_session_id TEXT,
  f_principal_workflow_id TEXT,
  f_principal_task_id TEXT,
  f_principal_agent_id TEXT,
  f_principal_authority TEXT,
  f_service_actor_session_id TEXT,
  f_service_actor_workflow_id TEXT,
  f_service_actor_task_id TEXT,
  f_service_actor_agent_id TEXT,
  f_service_actor_authority TEXT,
  f_base_conversation_version INTEGER,
  f_semantic_seq INTEGER,
  f_epoch INTEGER,
  f_policy_version TEXT,
  f_descriptor_version TEXT,
  f_request_hash TEXT,
  f_request_nil INTEGER NOT NULL DEFAULT 0,
  f_request BLOB,
  f_manifest_hash TEXT,
  f_proposal_hash TEXT,
  f_attempts INTEGER,
  f_outcome_hash TEXT,
  f_outcome_present INTEGER NOT NULL DEFAULT 0,
  f_outcome_attempt INTEGER,
  f_outcome_state TEXT,
  f_outcome_response_hash TEXT,
  f_outcome_response_nil INTEGER NOT NULL DEFAULT 0,
  f_outcome_response BLOB,
  f_outcome_failure_reason TEXT,
  f_outcome_retryable INTEGER,
  f_outcome_usage TEXT,
  f_reason TEXT,
  f_prepared_seq INTEGER,
  f_finished_seq INTEGER,
  f_revision INTEGER,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_attempt (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_state TEXT,
  f_outcome_hash TEXT,
  f_retryable INTEGER,
  f_provider_request_id TEXT,
  f_sent_seq INTEGER,
  f_finished_seq INTEGER,
  f_sent_at TEXT,
  f_finished_at TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE INDEX item_order ON rec_item(session_id,f_seq,id);
CREATE INDEX item_task ON rec_item(session_id,f_task_id);
CREATE INDEX relationship_order ON rec_relationship(session_id,f_seq,id);
CREATE INDEX relationship_from ON rec_relationship(session_id,f_type,f_from_id);
CREATE INDEX lifecycle_order ON rec_lifecycle(session_id,f_seq,id);
CREATE INDEX call_order ON rec_call(session_id,f_prepared_seq,id);
CREATE UNIQUE INDEX one_reserving_call ON rec_call(session_id,f_conversation_id) WHERE f_state IN ('PREPARED','SENT','UNKNOWN');
CREATE TABLE blobs (session_id TEXT NOT NULL, hash TEXT NOT NULL, media_type TEXT NOT NULL, data BLOB NOT NULL, data_nil INTEGER NOT NULL CHECK(data_nil IN (0,1)), PRIMARY KEY(session_id,hash), FOREIGN KEY(session_id) REFERENCES sessions(session_id));
CREATE TABLE directives (session_id TEXT NOT NULL, task_id TEXT NOT NULL, directive_id TEXT NOT NULL, boundary_scope TEXT NOT NULL, boundary_session_id TEXT NOT NULL, boundary_workflow_id TEXT NOT NULL, boundary_task_id TEXT NOT NULL, boundary_agent_id TEXT NOT NULL, item_id TEXT NOT NULL, PRIMARY KEY(session_id,task_id,directive_id,boundary_scope,boundary_session_id,boundary_workflow_id,boundary_task_id,boundary_agent_id), FOREIGN KEY(session_id) REFERENCES sessions(session_id));
