-- 0007: ingestion records (D14, D16, D1).
-- rec_envelope holds each accepted event's replayable request (blob bytes
-- replaced by references); rec_receipt its immutable result, with the
-- original item values in rec_receipt_item and the diagnostic and lifecycle
-- command records in rec_diagnostic and rec_command, which the receipt
-- references by ID in order. Every record is keyed by the event's
-- occurrence ID, so anonymous events never alias. No earlier rows exist.
CREATE TABLE rec_envelope (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_event_id TEXT,
  f_principal_session_id TEXT,
  f_principal_workflow_id TEXT,
  f_principal_task_id TEXT,
  f_principal_agent_id TEXT,
  f_principal_authority TEXT,
  f_event_event_id TEXT,
  f_event_kind TEXT,
  f_event_turn_boundary INTEGER,
  f_event_spans TEXT,
  f_payload_hash TEXT,
  f_schema_version TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_receipt (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_event_id TEXT,
  f_principal_session_id TEXT,
  f_principal_workflow_id TEXT,
  f_principal_task_id TEXT,
  f_principal_agent_id TEXT,
  f_principal_authority TEXT,
  f_payload_hash TEXT,
  f_seq INTEGER,
  f_opened_turn INTEGER,
  f_turn_id TEXT,
  f_item_count INTEGER,
  f_diagnostic_ids TEXT,
  f_command_ids TEXT,
  f_duplicates TEXT,
  f_replacements TEXT,
  f_versions_parser TEXT,
  f_versions_policy TEXT,
  f_versions_limits_max_span_bytes INTEGER,
  f_versions_limits_max_items_per_span INTEGER,
  f_versions_limits_max_diagnostics_per_span INTEGER,
  f_versions_limits_max_id_bytes INTEGER,
  f_versions_limits_max_heading_level INTEGER,
  f_versions_limits_max_heading_bytes INTEGER,
  f_versions_limits_max_attributes INTEGER,
  f_versions_limits_max_attribute_bytes INTEGER,
  f_versions_limits_max_spans INTEGER,
  f_versions_limits_max_parts INTEGER,
  f_versions_limits_max_event_bytes INTEGER,
  f_versions_limits_max_blob_bytes INTEGER,
  f_versions_limits_max_event_items INTEGER,
  f_versions_limits_max_event_diagnostics INTEGER,
  f_versions_limits_max_relationships INTEGER,
  f_schema_version TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_receipt_item (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_item_id TEXT,
  f_item_event_id TEXT,
  f_item_directive_id TEXT,
  f_item_section TEXT,
  f_item_role TEXT,
  f_item_seq INTEGER,
  f_item_session_id TEXT,
  f_item_workflow_id TEXT,
  f_item_task_id TEXT,
  f_item_agent_id TEXT,
  f_item_turn_id TEXT,
  f_item_kind TEXT,
  f_item_generation TEXT,
  f_item_authority TEXT,
  f_item_scope TEXT,
  f_item_access_scope TEXT,
  f_item_access_session_id TEXT,
  f_item_access_workflow_id TEXT,
  f_item_access_task_id TEXT,
  f_item_access_agent_id TEXT,
  f_item_residency TEXT,
  f_item_goal_status_present INTEGER NOT NULL DEFAULT 0,
  f_item_goal_status TEXT,
  f_item_retention TEXT,
  f_item_parts BLOB,
  f_item_content_hash TEXT,
  f_item_semantic_bytes INTEGER,
  f_item_importance INTEGER,
  f_item_created_at TEXT,
  f_item_last_used_call INTEGER,
  f_item_access_count INTEGER,
  f_item_ttl_turns_present INTEGER NOT NULL DEFAULT 0,
  f_item_ttl_turns INTEGER,
  f_item_created_turn INTEGER,
  f_item_tags TEXT,
  f_item_source_present INTEGER NOT NULL DEFAULT 0,
  f_item_source_kind TEXT,
  f_item_source_locator TEXT,
  f_item_source_content_hash TEXT,
  f_item_source_tool_call_id TEXT,
  f_item_source_ranges TEXT,
  f_item_version INTEGER,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_diagnostic (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_occurrence_id TEXT,
  f_event_id TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  f_schema_version TEXT,
  f_diagnostic_span_index INTEGER,
  f_diagnostic_part_index INTEGER,
  f_diagnostic_index INTEGER,
  f_diagnostic_code TEXT,
  f_diagnostic_reason TEXT,
  f_diagnostic_section TEXT,
  f_diagnostic_directive_id TEXT,
  f_diagnostic_range_start INTEGER,
  f_diagnostic_range_end INTEGER,
  f_diagnostic_parser_version TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_command (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_occurrence_id TEXT,
  f_event_id TEXT,
  f_ordinal INTEGER,
  f_actor_session_id TEXT,
  f_actor_workflow_id TEXT,
  f_actor_task_id TEXT,
  f_actor_agent_id TEXT,
  f_actor_authority TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  f_parser_version TEXT,
  f_schema_version TEXT,
  f_status TEXT,
  f_resolution TEXT,
  f_resolved_item_id TEXT,
  f_resolved_version INTEGER,
  f_lifecycle_command_action TEXT,
  f_lifecycle_command_target_id TEXT,
  f_lifecycle_command_authority TEXT,
  f_lifecycle_command_span_index INTEGER,
  f_lifecycle_command_part_index INTEGER,
  f_lifecycle_command_range_start INTEGER,
  f_lifecycle_command_range_end INTEGER,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE INDEX receipt_order ON rec_receipt(session_id,f_seq,id);
