-- 0022: Phase 3 resource registration and reporting, per-path content,
-- workspace bindings, pre-execution runs, typed observations, and subject
-- state (P3-19..22/41). Nothing is backfilled: no migration guesses a
-- repository, baseline fingerprint, reporter, binding, or run order.
CREATE TABLE rec_resource_binding (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_id TEXT,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_owner_session_id TEXT,
  f_owner_workflow_id TEXT,
  f_owner_task_id TEXT,
  f_owner_agent_id TEXT,
  f_owner_authority TEXT,
  f_reporter_session_id TEXT,
  f_reporter_workflow_id TEXT,
  f_reporter_task_id TEXT,
  f_reporter_agent_id TEXT,
  f_reporter_authority TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_resource_update (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_resource_id TEXT,
  f_request_id TEXT,
  f_reporter_session_id TEXT,
  f_reporter_workflow_id TEXT,
  f_reporter_task_id TEXT,
  f_reporter_agent_id TEXT,
  f_reporter_authority TEXT,
  f_expected_authoritative_revision INTEGER,
  f_resulting_authoritative_revision INTEGER,
  f_workspace_fingerprint TEXT,
  f_freshness TEXT,
  f_resynchronization INTEGER,
  f_all_paths INTEGER,
  f_changed_paths TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_resource_state (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_id TEXT,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_binding_id TEXT,
  f_last_update_id TEXT,
  f_authoritative_revision INTEGER,
  f_revision INTEGER,
  f_workspace_fingerprint TEXT,
  f_freshness TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_path_state (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_state_semantic_meta_id TEXT,
  f_state_semantic_meta_session_id TEXT,
  f_state_semantic_meta_schema_version TEXT,
  f_state_semantic_meta_seq INTEGER,
  f_state_locator_resource_id TEXT,
  f_state_locator_base_dir TEXT,
  f_state_locator_path TEXT,
  f_state_content_hash TEXT,
  f_state_resource_update_id TEXT,
  f_state_resource_revision INTEGER,
  f_state_revision INTEGER,
  f_state_freshness TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_workspace_binding (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_context_kind TEXT,
  f_context_id TEXT,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_resource_id TEXT,
  f_source_item_id TEXT,
  f_task_id TEXT,
  f_conversation_id TEXT,
  f_base_dir TEXT,
  f_environment_spec TEXT,
  f_suite_spec TEXT,
  f_coverage_spec TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  f_reporter_session_id TEXT,
  f_reporter_workflow_id TEXT,
  f_reporter_task_id TEXT,
  f_reporter_agent_id TEXT,
  f_reporter_authority TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_observation_run (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_subject_family TEXT,
  f_subject_target_tests_present INTEGER NOT NULL DEFAULT 0,
  f_subject_target_tests_resource_id TEXT,
  f_subject_target_tests_base_dir TEXT,
  f_subject_target_tests_working_dir TEXT,
  f_subject_target_tests_environment_spec TEXT,
  f_subject_target_tests_suite_spec TEXT,
  f_subject_target_tests_coverage_spec TEXT,
  f_subject_target_file_present INTEGER NOT NULL DEFAULT 0,
  f_subject_target_file_locator_resource_id TEXT,
  f_subject_target_file_locator_base_dir TEXT,
  f_subject_target_file_locator_path TEXT,
  f_subject_target_file_mode TEXT,
  f_subject_target_file_required_hash TEXT,
  f_subject_key TEXT,
  f_ordinal INTEGER,
  f_execution_id TEXT,
  f_binding_id TEXT,
  f_binding_version INTEGER,
  f_task_id TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  f_reporter_session_id TEXT,
  f_reporter_workflow_id TEXT,
  f_reporter_task_id TEXT,
  f_reporter_agent_id TEXT,
  f_reporter_authority TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_observation (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_family TEXT,
  f_run_id TEXT,
  f_execution_id TEXT,
  f_subject_key TEXT,
  f_evidence_item_id TEXT,
  f_binding_id TEXT,
  f_binding_version INTEGER,
  f_reporter_session_id TEXT,
  f_reporter_workflow_id TEXT,
  f_reporter_task_id TEXT,
  f_reporter_agent_id TEXT,
  f_reporter_authority TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  f_observed_workspace_fingerprint TEXT,
  f_observed_content_hash TEXT,
  f_outcome TEXT,
  f_completeness TEXT,
  f_passed INTEGER,
  f_failed INTEGER,
  f_skipped INTEGER,
  f_total INTEGER,
  f_reporting_matcher_name TEXT,
  f_reporting_matcher_version TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_subject_state (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_resource TEXT,
  f_first_seq INTEGER,
  f_state_semantic_meta_id TEXT,
  f_state_semantic_meta_session_id TEXT,
  f_state_semantic_meta_schema_version TEXT,
  f_state_semantic_meta_seq INTEGER,
  f_state_subject_key TEXT,
  f_state_task_id TEXT,
  f_state_current_item_id TEXT,
  f_state_observation_id TEXT,
  f_state_access_scope TEXT,
  f_state_access_session_id TEXT,
  f_state_access_workflow_id TEXT,
  f_state_access_task_id TEXT,
  f_state_access_agent_id TEXT,
  f_state_accepted_ordinal INTEGER,
  f_state_revision INTEGER,
  f_state_applicability TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE UNIQUE INDEX resource_binding_id ON rec_resource_binding(session_id,f_id);
CREATE UNIQUE INDEX resource_update_request ON rec_resource_update(session_id,f_resource_id,f_request_id);
CREATE INDEX resource_update_seq ON rec_resource_update(session_id,f_resource_id,f_seq,id);
CREATE INDEX workspace_binding_context ON rec_workspace_binding(session_id,f_context_kind,f_context_id,f_seq,id);
CREATE INDEX observation_run_subject ON rec_observation_run(session_id,f_subject_key,f_seq,id);
CREATE INDEX observation_by_run ON rec_observation(session_id,f_run_id,f_seq,id);
CREATE UNIQUE INDEX subject_state_id ON rec_subject_state(session_id,f_state_semantic_meta_id);
CREATE INDEX subject_state_resource ON rec_subject_state(session_id,f_resource,f_first_seq,f_state_semantic_meta_id);
