-- 0023: Phase 3 obligation declarations, applicability proofs and their
-- dependencies, assertions, and transition details, with the indexed
-- obligation reads completion and invalidation need (P3-9/12..18/23/41).
-- Nothing is backfilled: no legacy obligation gains a declaration, proof,
-- assertion mode, or dependency.
CREATE TABLE rec_obligation_declaration (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_declaration_semantic_meta_id TEXT,
  f_declaration_semantic_meta_session_id TEXT,
  f_declaration_semantic_meta_schema_version TEXT,
  f_declaration_semantic_meta_seq INTEGER,
  f_declaration_target_session_id TEXT,
  f_declaration_target_obligation_id TEXT,
  f_declaration_target_version INTEGER,
  f_declaration_declaration_slot TEXT,
  f_declaration_claim_pattern_version TEXT,
  f_declaration_source_item_id TEXT,
  f_declaration_workspace_binding_present INTEGER NOT NULL DEFAULT 0,
  f_declaration_workspace_binding_id TEXT,
  f_declaration_workspace_binding_version INTEGER,
  f_declaration_target_spec_present INTEGER NOT NULL DEFAULT 0,
  f_declaration_target_spec_tests_present INTEGER NOT NULL DEFAULT 0,
  f_declaration_target_spec_tests_resource_id TEXT,
  f_declaration_target_spec_tests_base_dir TEXT,
  f_declaration_target_spec_tests_working_dir TEXT,
  f_declaration_target_spec_tests_environment_spec TEXT,
  f_declaration_target_spec_tests_suite_spec TEXT,
  f_declaration_target_spec_tests_coverage_spec TEXT,
  f_declaration_target_spec_file_present INTEGER NOT NULL DEFAULT 0,
  f_declaration_target_spec_file_locator_resource_id TEXT,
  f_declaration_target_spec_file_locator_base_dir TEXT,
  f_declaration_target_spec_file_locator_path TEXT,
  f_declaration_target_spec_file_mode TEXT,
  f_declaration_target_spec_file_required_hash TEXT,
  f_declaration_matcher_present INTEGER NOT NULL DEFAULT 0,
  f_declaration_matcher_name TEXT,
  f_declaration_matcher_version TEXT,
  f_declaration_binding TEXT,
  f_declaration_diagnostic TEXT,
  f_declaration_actor_session_id TEXT,
  f_declaration_actor_workflow_id TEXT,
  f_declaration_actor_task_id TEXT,
  f_declaration_actor_agent_id TEXT,
  f_declaration_actor_authority TEXT,
  f_declaration_grant_id TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_proof (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_evidence_ids TEXT,
  f_resource_id TEXT,
  f_fingerprint TEXT,
  f_path_content_hash TEXT,
  f_resource_revision INTEGER,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_target_session_id TEXT,
  f_target_obligation_id TEXT,
  f_target_version INTEGER,
  f_target_spec_hash TEXT,
  f_transition_id TEXT,
  f_evidence_coverage_id TEXT,
  f_matcher_present INTEGER NOT NULL DEFAULT 0,
  f_matcher_name TEXT,
  f_matcher_version TEXT,
  f_rule_version TEXT,
  f_observation_id TEXT,
  f_assertion_id TEXT,
  f_dependency_ids TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_proof_dependency (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_proof_id TEXT,
  f_resource_id TEXT,
  f_kind TEXT,
  f_resource_revision INTEGER,
  f_fingerprint TEXT,
  f_locator_present INTEGER NOT NULL DEFAULT 0,
  f_locator_resource_id TEXT,
  f_locator_base_dir TEXT,
  f_locator_path TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_assertion (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_target_session_id TEXT,
  f_target_obligation_id TEXT,
  f_target_version INTEGER,
  f_mode TEXT,
  f_actor_session_id TEXT,
  f_actor_workflow_id TEXT,
  f_actor_task_id TEXT,
  f_actor_agent_id TEXT,
  f_actor_authority TEXT,
  f_grant_id TEXT,
  f_transition_id TEXT,
  f_evidence_coverage_id TEXT,
  f_proof_id TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_transition_detail (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_id TEXT,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_target_session_id TEXT,
  f_target_obligation_id TEXT,
  f_target_version INTEGER,
  f_cause TEXT,
  f_proof_id TEXT,
  f_previous_proof_id TEXT,
  f_assertion_id TEXT,
  f_resource_update_id TEXT,
  f_observation_id TEXT,
  f_rule_version TEXT,
  f_origin_authorization_present INTEGER NOT NULL DEFAULT 0,
  f_origin_authorization_transition_id TEXT,
  f_origin_authorization_grant_id TEXT,
  f_origin_authorization_actor_session_id TEXT,
  f_origin_authorization_actor_workflow_id TEXT,
  f_origin_authorization_actor_task_id TEXT,
  f_origin_authorization_actor_agent_id TEXT,
  f_origin_authorization_actor_authority TEXT,
  f_origin_authorization_target_session_id TEXT,
  f_origin_authorization_target_obligation_id TEXT,
  f_origin_authorization_target_version INTEGER,
  f_origin_authorization_seq INTEGER,
  f_private_rationale TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE UNIQUE INDEX obligation_declaration_id ON rec_obligation_declaration(session_id,f_declaration_semantic_meta_id);
CREATE INDEX proof_dependency_proof ON rec_proof_dependency(session_id,f_proof_id,f_seq,id);
CREATE INDEX transition_version ON rec_obligation_transition(session_id,f_obligation_id,f_version,f_seq,id);
-- Current versions owned by a task's TURN/TASK scope (completion), and
-- current bound versions by observation subject (matcher evaluation).
CREATE INDEX obligation_task_owner ON rec_obligation(session_id,f_access_task_id,f_created_seq,id) WHERE f_current=1 AND f_access_scope IN ('TASK','TURN');
CREATE INDEX obligation_bound_subject ON rec_obligation(session_id,f_target_subject_key,f_created_seq,id) WHERE f_current=1 AND f_binding_state='BOUND';
-- Dependencies of every current proof (a current version's current proof),
-- maintained as proofs become and stop being current (P3-23): path_key is
-- a path dependency's canonical locator key, or empty for a workspace-level
-- dependency.
CREATE TABLE lookup_live_dependency (
  session_id TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  path_key TEXT NOT NULL,
  seq INTEGER NOT NULL,
  proof_id TEXT NOT NULL,
  PRIMARY KEY (session_id,resource_id,path_key,seq,proof_id)
);
CREATE INDEX live_dependency_resource ON lookup_live_dependency(session_id,resource_id,seq,proof_id);
