-- 0024: Phase 3 retrieval leases, results, projections, and events
-- (P3-28..30/41). No legacy content gains a lease or admission, and no
-- item's residency changes: retrieval is admission, recorded here, never a
-- mutation of the source.
CREATE TABLE rec_retrieval_lease (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_holder_session_id TEXT,
  f_holder_workflow_id TEXT,
  f_holder_task_id TEXT,
  f_holder_agent_id TEXT,
  f_holder_authority TEXT,
  f_conversation_id TEXT,
  f_turn_id TEXT,
  f_source_item_id TEXT,
  f_source_content_hash TEXT,
  f_issued_completed_inference_index INTEGER,
  f_call_allowance INTEGER,
  f_policy_version TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_retrieval_result (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_request_id TEXT,
  f_lease_id TEXT,
  f_projection_id TEXT,
  f_retrieval_event_id TEXT,
  f_origin_holder_session_id TEXT,
  f_origin_holder_workflow_id TEXT,
  f_origin_holder_task_id TEXT,
  f_origin_holder_agent_id TEXT,
  f_origin_holder_authority TEXT,
  f_origin_conversation_id TEXT,
  f_origin_turn_id TEXT,
  f_origin_invocation_present INTEGER NOT NULL DEFAULT 0,
  f_origin_invocation_session_id TEXT,
  f_origin_invocation_conversation_id TEXT,
  f_origin_invocation_call_id TEXT,
  f_origin_invocation_tool_call_id TEXT,
  f_origin_invocation_exchange_id TEXT,
  f_origin_invocation_turn_id TEXT,
  f_origin_invocation_principal_session_id TEXT,
  f_origin_invocation_principal_workflow_id TEXT,
  f_origin_invocation_principal_task_id TEXT,
  f_origin_invocation_principal_agent_id TEXT,
  f_origin_invocation_principal_authority TEXT,
  f_observed_source_item_id TEXT,
  f_observed_source_content_hash TEXT,
  f_observed_version INTEGER,
  f_observed_currentness TEXT,
  f_observed_goal_status_present INTEGER NOT NULL DEFAULT 0,
  f_observed_goal_status TEXT,
  f_observed_generation TEXT,
  f_observed_residency TEXT,
  f_observed_authority TEXT,
  f_observed_expiry TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  f_policy_version TEXT,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_projection (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_item_id TEXT,
  f_source_item_id TEXT,
  f_source_content_hash TEXT,
  f_lease_id TEXT,
  f_retrieval_result_id TEXT,
  f_dependency_coverage_id TEXT,
  f_origin_holder_session_id TEXT,
  f_origin_holder_workflow_id TEXT,
  f_origin_holder_task_id TEXT,
  f_origin_holder_agent_id TEXT,
  f_origin_holder_authority TEXT,
  f_origin_conversation_id TEXT,
  f_origin_turn_id TEXT,
  f_origin_invocation_present INTEGER NOT NULL DEFAULT 0,
  f_origin_invocation_session_id TEXT,
  f_origin_invocation_conversation_id TEXT,
  f_origin_invocation_call_id TEXT,
  f_origin_invocation_tool_call_id TEXT,
  f_origin_invocation_exchange_id TEXT,
  f_origin_invocation_turn_id TEXT,
  f_origin_invocation_principal_session_id TEXT,
  f_origin_invocation_principal_workflow_id TEXT,
  f_origin_invocation_principal_task_id TEXT,
  f_origin_invocation_principal_agent_id TEXT,
  f_origin_invocation_principal_authority TEXT,
  f_access_scope TEXT,
  f_access_session_id TEXT,
  f_access_workflow_id TEXT,
  f_access_task_id TEXT,
  f_access_agent_id TEXT,
  f_delivery_policy_version TEXT,
  f_omitted_bytes INTEGER,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE TABLE rec_retrieval_event (
  session_id TEXT NOT NULL,
  id TEXT NOT NULL,
  subkey INTEGER NOT NULL DEFAULT 0,
  f_schema_version TEXT,
  f_seq INTEGER,
  f_request_id TEXT,
  f_principal_session_id TEXT,
  f_principal_workflow_id TEXT,
  f_principal_task_id TEXT,
  f_principal_agent_id TEXT,
  f_principal_authority TEXT,
  f_triggering_actor_session_id TEXT,
  f_triggering_actor_workflow_id TEXT,
  f_triggering_actor_task_id TEXT,
  f_triggering_actor_agent_id TEXT,
  f_triggering_actor_authority TEXT,
  f_invocation_id TEXT,
  f_result_id TEXT,
  f_source_present INTEGER NOT NULL DEFAULT 0,
  f_source_item_id TEXT,
  f_source_content_hash TEXT,
  f_error_code TEXT,
  f_latency_nanos INTEGER,
  PRIMARY KEY (session_id,id,subkey),
  FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);
CREATE INDEX lease_holder ON rec_retrieval_lease(session_id,f_conversation_id,f_turn_id,f_holder_task_id,f_holder_agent_id,f_seq,id);
CREATE INDEX lease_source ON rec_retrieval_lease(session_id,f_source_item_id,f_source_content_hash,f_seq,id);
CREATE UNIQUE INDEX projection_item ON rec_projection(session_id,f_item_id);
CREATE INDEX retrieval_event_request ON rec_retrieval_event(session_id,f_request_id,f_seq,id);
