package sqlitetest

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/tdavison784/context-runtime/internal/domain"
)

// The frozen Phase 2 fixture (P3-40/41): testdata/phase2/phase2.db was
// written by the merged Phase 2 binary (commit b5f6b1f) running
// testdata/phase2/gen.go, and manifest.json is the logical state that
// binary read back. Neither file is ever regenerated by a later tree.

//go:embed testdata/phase2/phase2.db
var phase2DB []byte

//go:embed testdata/phase2/manifest.json
var phase2Manifest []byte

// Phase2Session is one session's state as the Phase 2 binary read it.
type Phase2Session struct {
	LastSeq       uint64
	Items         []domain.ContextItem
	Relationships []domain.Relationship
	Events        []domain.EventRecord
	Obligations   []domain.ObligationVersion
	Transitions   []domain.ObligationTransition
	Grants        []domain.MutationGrant
	Tasks         []domain.TaskState
	Lifecycle     []domain.LifecycleEvent
	Receipts      []domain.IngestReceipt
	Envelopes     []domain.EventEnvelope
	Diagnostics   []domain.DiagnosticRecord
	Commands      []domain.LifecycleCommandRecord
	Conversations []domain.Conversation
	Calls         []domain.CallRecord
	Attempts      []domain.CallAttempt
}

// Phase2Manifest is the fixture's recorded state: occurrence IDs and the
// viewer used for access-filtered reads, per session.
type Phase2Manifest struct {
	BaseCommit  string
	Occurrences map[string][]string
	Viewers     map[string]domain.Principal
	Sessions    map[string]Phase2Session
}

// Phase2Path returns a private copy of the Phase 2 database, so a test can
// upgrade it without touching the committed file.
func Phase2Path(t testing.TB) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "phase2.db")
	if err := os.WriteFile(path, phase2DB, 0600); err != nil {
		t.Fatal(err)
	}
	return path
}

// Phase2 decodes the manifest into the current record types. Decoding is
// strict: a field the Phase 2 binary wrote that the current types no longer
// have fails the test instead of being dropped; fields added since decode
// as their zero values, which is the legacy form.
func Phase2(t testing.TB) Phase2Manifest {
	t.Helper()
	var m Phase2Manifest
	dec := json.NewDecoder(bytes.NewReader(phase2Manifest))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&m); err != nil {
		t.Fatalf("decode Phase 2 manifest: %v", err)
	}
	return m
}
